baseurl = "http://hugo.spf13.com/"
languageCode = "en-us"
title = "Data Scientology"
theme = "hugo-future-imperfect"
preserveTaxonomyNames = true
paginate = 3
googleAnalytics = ""
pluralizeListTitles = false

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "An above average blog, written by an average guy."
    # This will appear on the top left of the navigation bar
    navbarTitle = "Carpe Diem"
    # set this to the section name if section is not post
    viewMorePostLink     = "/blog/"

# Optional Params
    # This will match the navbarTitle to the section of the website
    dynamicTitles        = true
    # RSS icon that appear on the sidebar, next to the social media buttons
    rssAppearAtTop       = false
    rssAppearAtBottom    = false
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Disable showing the social sharing links on blog posts
    socialShareDisabled = false

    # Load custom CSS or JavaScript files. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    customCSS            = ["default"]
    customJS             = ["default"]


# parms.intro will appear on the sidebar
# This is optional, but it's suggested to use
[params.intro]
    header    = "Data Scientology"

    paragraph = "Let me help you better understand data science."

    about     = "My name is Joshua Lammon and I am a dual major in Business & Competitive Intelligence and Finance with a minor in Information Technology at Mercyhurst University. This blog is intended to illustrate data science techniques that I learned in an Introduction to Data Science course."

# This will also appear on the sidebar.
# A width of less than 100px is recommended
# This is optional
[params.intro.pic]
    src       = "/img/main/Lammon2.jpg"
    # modify your picture in the shape of a circle or
    # future imperfect's hexagonal shape
    circle    = true
    imperfect = false
    width     = "125"
    alt       = "Hugo Future Imperfect"

# Adjust the amount of recent posts on the sidebar.
# This is optional. The default value 5 will be used
[params.postAmount]
    sidebar = 2

# Set up your menu items in the navigation bar
# You can use identifier to prepend a font awesome icon to your text

[[menu.main]]
    name = "Humble Abode"
    url = "/"
    identifier = "fa fa-home"
    weight = 1

[[menu.main]]
    name = "About Me"
    url = "/about/"
    identifier = "fa fa-id-card-o"
    weight = 2

[[menu.main]]
    name = "Blog - Read Me"
    url = "/blog/"
    identifier = "fa fa-newspaper-o"
    weight = 3

[[menu.main]]
    name = "Itemized"
    url = "/itemized/"
    identifier = "fa fa-list"
    weight = 4

[[menu.main]]
    name = "Neat Topics"
    url = "/categories/"
    identifier = "fa fa-sitemap"
    weight = 5

[[menu.main]]
    name = "Slide Into My DM's"
    url = "/contact/"
    identifier = "fa fa-envelope-o"
    weight = 6

# Insert your username and the icon will apear on the page as long as
# socialAppearAtTop or socialAppearAtBottom is set to true in the params area
# The social media icons will appear on the sidebar
[social]
    linkedin        = "joshua-lammon"
    github          = "Lammchops71"
    bitbucket       = ""
    jsfiddle        = ""
    codepen         = ""
    foursquare      = ""
    dribbble        = ""
    deviantart      = ""
    behance         = ""
    flickr          = ""
    instagram       = "Lammchops71"
    youtube         = ""
    vimeo           = ""
    vine            = ""
    medium          = ""
    wordpress       = ""
    tumblr          = ""
    xing            = ""
    slideshare      = ""
    stackoverflow   = ""
    reddit          = ""
    pinterest       = ""
    googleplus      = ""
    facebook        = "joshua.lammon"
    facebook_admin  = ""
    twitter_domain  = ""
    twitter         = "Lammchops71"
    email           = "jlammo94@lakers.mercyhurst.edu"
